spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:commerceops_admin}
    username: ${DB_USERNAME:commerceops}
    password: ${DB_PASSWORD:commerceops}
  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false

logging:
  level:
    com.commerceops.admin: DEBUG
