package com.commerceops.admin.audit.model;

public enum AuditAction {
    AUTH_LOGIN_SUCCESS,
    AUTH_LOGIN_FAILURE,
    ADMIN_USER_CREATED,
    ADMIN_USER_UPDATED,
    PRODUCT_CREATED,
    PRODUCT_UPDATED,
    PRODUCT_DELETED,
    CATEGORY_CREATED,
    CATEGORY_UPDATED,
    CATEGORY_DELETED,
    CUSTOMER_CREATED,
    CUSTOMER_UPDATED,
    CUSTOMER_DELETED,
    ORDER_STATUS_CHANGED,
    ORDER_CANCELLED,
    ORDER_REFUNDED,
    COUPON_CREATED,
    COUPON_UPDATED,
    COUPON_DELETED,
    COUPON_ACTIVATED,
    COUPON_DEACTIVATED
}
