CREATE TABLE role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    description VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_role_name UNIQUE (name)
);

CREATE TABLE admin_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(190) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    status VARCHAR(30) NOT NULL,
    last_login_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMP WITH TIME ZONE,
    deleted_by BIGINT,
    CONSTRAINT uk_admin_user_public_id UNIQUE (public_id),
    CONSTRAINT uk_admin_user_email UNIQUE (email)
);

CREATE TABLE admin_user_role (
    admin_user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    CONSTRAINT pk_admin_user_role PRIMARY KEY (admin_user_id, role_id),
    CONSTRAINT fk_admin_user_role_admin_user FOREIGN KEY (admin_user_id) REFERENCES admin_user (id),
    CONSTRAINT fk_admin_user_role_role FOREIGN KEY (role_id) REFERENCES role (id)
);

CREATE INDEX idx_admin_user_public_id ON admin_user (public_id);
CREATE INDEX idx_admin_user_email ON admin_user (email);
CREATE INDEX idx_admin_user_status ON admin_user (status);
CREATE INDEX idx_admin_user_role_admin_user_id ON admin_user_role (admin_user_id);
CREATE INDEX idx_admin_user_role_role_id ON admin_user_role (role_id);

INSERT INTO role (name, description, created_at, updated_at) VALUES
('ADMIN', 'Full system access.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('MANAGER', 'Operational management access.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('SUPPORT', 'Customer and order support access.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('CATALOG', 'Catalog management access.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('READ_ONLY', 'Read-only administrative access.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
