CREATE TABLE category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL,
    parent_id BIGINT,
    name VARCHAR(120) NOT NULL,
    slug VARCHAR(160) NOT NULL,
    description VARCHAR(1000),
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMP WITH TIME ZONE,
    deleted_by BIGINT,
    CONSTRAINT uk_category_public_id UNIQUE (public_id),
    CONSTRAINT fk_category_parent FOREIGN KEY (parent_id) REFERENCES category (id),
    CONSTRAINT ck_category_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE INDEX idx_category_public_id ON category (public_id);
CREATE INDEX idx_category_slug ON category (slug);
CREATE INDEX idx_category_status ON category (status);
CREATE INDEX idx_category_parent_id ON category (parent_id);
CREATE UNIQUE INDEX uk_category_active_slug ON category (slug) ${activeUniquePredicate};
