CREATE TABLE product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL,
    category_id BIGINT NOT NULL,
    sku VARCHAR(80) NOT NULL,
    name VARCHAR(180) NOT NULL,
    slug VARCHAR(200) NOT NULL,
    description VARCHAR(2000),
    price NUMERIC(19, 2) NOT NULL,
    image_url VARCHAR(2048),
    stock_quantity INTEGER NOT NULL,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMP WITH TIME ZONE,
    deleted_by BIGINT,
    CONSTRAINT uk_product_public_id UNIQUE (public_id),
    CONSTRAINT fk_product_category FOREIGN KEY (category_id) REFERENCES category (id),
    CONSTRAINT ck_product_price CHECK (price >= 0),
    CONSTRAINT ck_product_stock_quantity CHECK (stock_quantity >= 0),
    CONSTRAINT ck_product_status CHECK (status IN ('DRAFT', 'ACTIVE', 'INACTIVE', 'OUT_OF_STOCK'))
);

CREATE INDEX idx_product_public_id ON product (public_id);
CREATE INDEX idx_product_sku ON product (sku);
CREATE INDEX idx_product_status ON product (status);
CREATE INDEX idx_product_category_id ON product (category_id);
CREATE UNIQUE INDEX uk_product_active_sku ON product (sku) ${activeUniquePredicate};
