CREATE TABLE customer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL,
    name VARCHAR(160) NOT NULL,
    email VARCHAR(190),
    phone VARCHAR(30),
    document VARCHAR(50),
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMP WITH TIME ZONE,
    deleted_by BIGINT,
    CONSTRAINT uk_customer_public_id UNIQUE (public_id),
    CONSTRAINT ck_customer_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'BLOCKED'))
);

CREATE UNIQUE INDEX uk_customer_active_email ON customer (email) ${customerEmailUniquePredicate};
CREATE INDEX idx_customer_public_id ON customer (public_id);
CREATE INDEX idx_customer_email ON customer (email);
CREATE INDEX idx_customer_status ON customer (status);
CREATE INDEX idx_customer_created_at ON customer (created_at);
