CREATE TABLE customer_note (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL,
    customer_id BIGINT NOT NULL,
    note VARCHAR(4000) NOT NULL,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMP WITH TIME ZONE,
    deleted_by BIGINT,
    CONSTRAINT uk_customer_note_public_id UNIQUE (public_id),
    CONSTRAINT fk_customer_note_customer FOREIGN KEY (customer_id) REFERENCES customer (id),
    CONSTRAINT fk_customer_note_created_by FOREIGN KEY (created_by) REFERENCES admin_user (id)
);

CREATE INDEX idx_customer_note_customer_id ON customer_note (customer_id);
CREATE INDEX idx_customer_note_public_id ON customer_note (public_id);
