CREATE TABLE sales_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL,
    customer_id BIGINT NOT NULL,
    order_number VARCHAR(50) NOT NULL,
    status VARCHAR(30) NOT NULL,
    subtotal_amount NUMERIC(19, 2) NOT NULL,
    discount_amount NUMERIC(19, 2) NOT NULL,
    shipping_amount NUMERIC(19, 2) NOT NULL,
    total_amount NUMERIC(19, 2) NOT NULL,
    payment_status VARCHAR(30) NOT NULL,
    delivery_status VARCHAR(30) NOT NULL,
    cancelled_at TIMESTAMP WITH TIME ZONE,
    refunded_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMP WITH TIME ZONE,
    deleted_by BIGINT,
    CONSTRAINT uk_sales_order_public_id UNIQUE (public_id),
    CONSTRAINT uk_sales_order_order_number UNIQUE (order_number),
    CONSTRAINT fk_sales_order_customer FOREIGN KEY (customer_id) REFERENCES customer (id),
    CONSTRAINT ck_sales_order_status CHECK (
        status IN ('PENDING', 'PAID', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'REFUNDED')
    ),
    CONSTRAINT ck_sales_order_payment_status CHECK (payment_status IN ('PENDING', 'PAID', 'FAILED', 'REFUNDED')),
    CONSTRAINT ck_sales_order_delivery_status CHECK (
        delivery_status IN ('PENDING', 'PREPARING', 'SHIPPED', 'DELIVERED', 'CANCELLED')
    ),
    CONSTRAINT ck_sales_order_amounts CHECK (
        subtotal_amount >= 0 AND discount_amount >= 0 AND shipping_amount >= 0 AND total_amount >= 0
    )
);

CREATE INDEX idx_sales_order_public_id ON sales_order (public_id);
CREATE INDEX idx_sales_order_customer_id ON sales_order (customer_id);
CREATE INDEX idx_sales_order_status ON sales_order (status);
CREATE INDEX idx_sales_order_created_at ON sales_order (created_at);
