CREATE TABLE order_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL,
    sales_order_id BIGINT NOT NULL,
    product_id BIGINT,
    product_sku VARCHAR(80) NOT NULL,
    product_name VARCHAR(180) NOT NULL,
    unit_price NUMERIC(19, 2) NOT NULL,
    quantity INTEGER NOT NULL,
    total_amount NUMERIC(19, 2) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_order_item_public_id UNIQUE (public_id),
    CONSTRAINT fk_order_item_sales_order FOREIGN KEY (sales_order_id) REFERENCES sales_order (id),
    CONSTRAINT fk_order_item_product FOREIGN KEY (product_id) REFERENCES product (id),
    CONSTRAINT ck_order_item_unit_price CHECK (unit_price >= 0),
    CONSTRAINT ck_order_item_quantity CHECK (quantity > 0),
    CONSTRAINT ck_order_item_total_amount CHECK (total_amount >= 0)
);

CREATE INDEX idx_order_item_sales_order_id ON order_item (sales_order_id);
CREATE INDEX idx_order_item_product_id ON order_item (product_id);
