CREATE TABLE order_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL,
    sales_order_id BIGINT NOT NULL,
    from_status VARCHAR(30) NOT NULL,
    to_status VARCHAR(30) NOT NULL,
    changed_by BIGINT NOT NULL,
    reason VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_order_status_history_public_id UNIQUE (public_id),
    CONSTRAINT fk_order_status_history_sales_order FOREIGN KEY (sales_order_id) REFERENCES sales_order (id),
    CONSTRAINT fk_order_status_history_changed_by FOREIGN KEY (changed_by) REFERENCES admin_user (id)
);

CREATE INDEX idx_order_status_history_sales_order_id ON order_status_history (sales_order_id);
CREATE INDEX idx_order_status_history_created_at ON order_status_history (created_at);
