CREATE TABLE coupon (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL,
    code VARCHAR(80) NOT NULL,
    description VARCHAR(1000),
    discount_type VARCHAR(30) NOT NULL,
    discount_value NUMERIC(19, 2) NOT NULL,
    starts_at TIMESTAMP WITH TIME ZONE,
    ends_at TIMESTAMP WITH TIME ZONE,
    usage_limit INTEGER,
    usage_count INTEGER NOT NULL DEFAULT 0,
    per_customer_limit INTEGER,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMP WITH TIME ZONE,
    deleted_by BIGINT,
    CONSTRAINT uk_coupon_public_id UNIQUE (public_id),
    CONSTRAINT ck_coupon_discount_type CHECK (discount_type IN ('FIXED_AMOUNT', 'PERCENTAGE')),
    CONSTRAINT ck_coupon_discount_value CHECK (
        discount_value > 0
        AND (discount_type <> 'PERCENTAGE' OR discount_value <= 100)
    ),
    CONSTRAINT ck_coupon_validity CHECK (starts_at IS NULL OR ends_at IS NULL OR ends_at > starts_at),
    CONSTRAINT ck_coupon_usage_limit CHECK (usage_limit IS NULL OR usage_limit > 0),
    CONSTRAINT ck_coupon_usage_count CHECK (usage_count >= 0),
    CONSTRAINT ck_coupon_per_customer_limit CHECK (per_customer_limit IS NULL OR per_customer_limit > 0),
    CONSTRAINT ck_coupon_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'EXPIRED'))
);

CREATE UNIQUE INDEX uk_coupon_active_code ON coupon (code) ${activeUniquePredicate};
CREATE INDEX idx_coupon_public_id ON coupon (public_id);
CREATE INDEX idx_coupon_code ON coupon (code);
CREATE INDEX idx_coupon_status ON coupon (status);
CREATE INDEX idx_coupon_starts_at ON coupon (starts_at);
CREATE INDEX idx_coupon_ends_at ON coupon (ends_at);
