CREATE TABLE audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL,
    actor_user_id BIGINT,
    actor_email VARCHAR(190),
    action VARCHAR(60) NOT NULL,
    entity_type VARCHAR(100),
    entity_public_id UUID,
    trace_id VARCHAR(100),
    request_method VARCHAR(20),
    request_path VARCHAR(1000),
    metadata_json TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_audit_log_public_id UNIQUE (public_id),
    CONSTRAINT fk_audit_log_actor_user FOREIGN KEY (actor_user_id) REFERENCES admin_user (id),
    CONSTRAINT ck_audit_log_action CHECK (action IN (
        'AUTH_LOGIN_SUCCESS',
        'AUTH_LOGIN_FAILURE',
        'ADMIN_USER_CREATED',
        'ADMIN_USER_UPDATED',
        'PRODUCT_CREATED',
        'PRODUCT_UPDATED',
        'PRODUCT_DELETED',
        'CATEGORY_CREATED',
        'CATEGORY_UPDATED',
        'CATEGORY_DELETED',
        'CUSTOMER_CREATED',
        'CUSTOMER_UPDATED',
        'CUSTOMER_DELETED',
        'ORDER_STATUS_CHANGED',
        'ORDER_CANCELLED',
        'ORDER_REFUNDED',
        'COUPON_CREATED',
        'COUPON_UPDATED',
        'COUPON_DELETED',
        'COUPON_ACTIVATED',
        'COUPON_DEACTIVATED'
    ))
);

CREATE INDEX idx_audit_log_actor_user_id ON audit_log (actor_user_id);
CREATE INDEX idx_audit_log_actor_email ON audit_log (actor_email);
CREATE INDEX idx_audit_log_action ON audit_log (action);
CREATE INDEX idx_audit_log_entity_type ON audit_log (entity_type);
CREATE INDEX idx_audit_log_entity_public_id ON audit_log (entity_public_id);
CREATE INDEX idx_audit_log_created_at ON audit_log (created_at);
